<?php
header('Content-Type: application/json');
require '../vendor/autoload.php';
require '../src/Client.php';

use CloudRebue\Client;

$account_id = "0278933ad3f9fe59c13245cf4a4cfdcf"; // Account Id from Bulk Portal
$api_key = "01a767c85d8673c80c4dfb264399dea795d712227ee1eb780c61c736981bdddf80b24ce5a14acf8eabc69378e41dafebbd1596cc97beef79d9807aa839221a02"; // Api Key from Bulk Portal

$client      = new Client($account_id, $api_key);

$sender = 'CLOUD_REBUE'; //The Sender ID to send the message with
$message = 'Test message'; //Short Message to be sent
$phone = '0708361797'; //phone number separeted with commas, MAX of 100 at a time
$endpoint =null; //Your endpoint that we will call to send delivery receipt for a given message. 
$correlator = "101"; // A Unique identifier generated by YOUR system, for each message. We forward delivery receipts together with your correlator, to help you identify the message in your system associated with the delivery receipt
$link_id = null; //An initiator identifier that was sent by an originating message, MUST be provided when sending on-demand messages

$response   = $client->send($sender, $message, $phone, $endpoint,$link_id, $correlator); //actual sending
print_r(json_encode($response));
